### ISSUE TITLE
[BUG] Rendering issue

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-mermaid-pop#2]
![image](https://github.com/user-attachments/assets/8f41a1ac-d0cf-4161-ad44-592d666d3887)

As the above image shows, after updating to new version, the Gantt rendering would be stretched.
And the multiple pop ups appear again, very strange!

Just after updating, it all works fine.
But after re-open the page, the gantt broken.

**Comment by gitcpy** [comment]
For the new way to open the popup, maybe  I will update it later.

**Comment by gitcpy** [comment]
I made a release 0.2.21, It is hard coded to open popup with ctrl+left click. It is a compromised way. May be I will make a progress in one of next version.

**Comment by Moyf** [comment]
Just updated to 0.2.21
- Ctrl+Click: Works fine
- Render issues: Fixed

- However, the "Multiple pop-ups" still exists on my end🤔
![image](https://github.com/user-attachments/assets/f10baa48-bc61-4aab-b7a1-61d8a3dbbdf2)

**Comment by Moyf** [comment]
> > > Just updated to 0.2.21
> > > 
> > > * Ctrl+Click: Works fine
> > > * Render issues: Fixed
> > > * However, the "Multiple pop-ups" still exists on my end🤔
> > >   ![image](https://private-user-images.githubusercontent.com/4013062/366851570-f10baa48-bc61-4aab-b7a1-61d8a3dbbdf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDEzNzIsIm5iZiI6MTcyNjE0MTA3MiwicGF0aCI6Ii80MDEzMDYyLzM2Njg1MTU3MC1mMTBiYWE0OC1iYzYxLTRhYWItYjdhMS02MWQ4YTNkYmJkZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTEzNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiMmU4Njk1OWU1OTc1NjhkZDdjNmUzMGZlMWU5M2VlYTM3ZjNmMDBlYzcyZThhYzZhMTk3MTI5NTk2NmNjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2z11YtT4c9Yep_seIMqOMiGwyD5TnFIQbRgGT5waaKo)
> > 
> > 
> > BTW (Sorry my thoguhts are too much 😹), it would be great if `Esc` could close the pop-up window
> 
> "Esc to close popup", done. But I did fix the bug -- multi-popups. Just try to clear the plugin, and install it by 'Brat' again, or make sure how to repeat the bug, and leave messages here. Then I will check it again.

Yap, when I use Obsidian on my computer in my home, it works fine. Tomorrow I'll double check it in my corp  : )
Thanks again!

**Comment by Moyf** [comment]
Wait a minute..
Just reading the commits and found out Chinese comment LOL

所以可以直接用中文交流对吧？
总之更新之后在家里和电脑上都正常了！棒！

**Comment by gitcpy** [comment]
试试这个&nbsp;https://github.com/gitcpy/mermaid-zoom-drag
这个支持全屏模式和触屏操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] [BUG] Rendering issue (Issue #2)





 
Wait a minute..
 Just reading the commits and found out Chinese comment LOL
 
所以可以直接用中文交流对吧？
 总之更新之后在家里和电脑上都正常了！棒！

**Comment by Moyf** [comment]
> 试试这个&nbsp;https://github.com/gitcpy/mermaid-zoom-drag 这个支持全屏模式和触屏操作
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/obsidian-mermaid-pop" ***@***.***&gt;; 发送时间:&nbsp;2024年9月14日(星期六) 下午3:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] [BUG] Rendering issue (Issue #2) Wait a minute.. Just reading the commits and found out Chinese comment LOL 所以可以直接用中文交流对吧？ 总之更新之后在家里和电脑上都正常了！棒！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哈哈试过了！我其实是先看到有群友推荐的 Zoom-Drag 的，然后在那边看到 Pop 然后来用。
目前我个人更喜欢 Pop 的操作逻辑！

不过奇怪的是刚才又出现了弹两次的情况，嗐。
好在 `Esc` 可以一次性关掉，所以感觉也还好。
回头我要是发现什么复现的线索再来补充更详细的信息吧~

**Comment by gitcpy** [comment]
基本，一开始，我只开发了内嵌的 mermaid-zoom-drag， 想节省很多操作，主要是 pc 上操作
后来觉得操作区域小了， 就额外做一个弹窗 obsidian-mermaid-pop, 可以弹窗嘛，自然操作好些
然后 github 有个哥们，把第一个的操作做了完善，后来还加上了全屏和触屏
可是那个哥们还不够，还要支持键盘操作，也就是说 第一个已经比第二个还完善，
至于第二个，按理没有你说的bug了，因为 是代码判断保证，但也不排除有其他触发bug，只不过我这边重现不了
你看着办两个都好用，另外，我应该就是你说的群里的朋友了， 只不过我确实没什么时间，只能保证不出bug，能顺利使用，其他的没办法保证。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] [BUG] Rendering issue (Issue #2)





  
试试这个&nbsp;https://github.com/gitcpy/mermaid-zoom-drag 这个支持全屏模式和触屏操作
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/obsidian-mermaid-pop" @.&gt;; 发送时间:&nbsp;2024年9月14日(星期六) 下午3:31 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] [BUG] Rendering issue (Issue #2) Wait a minute.. Just reading the commits and found out Chinese comment LOL 所以可以直接用中文交流对吧？ 总之更新之后在家里和电脑上都正常了！棒！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
哈哈试过了！我其实是先看到有群友推荐的 Zoom-Drag 的，然后在那边看到 Pop 然后来用。
 目前我个人更喜欢 Pop 的操作逻辑！
 
不过奇怪的是刚才又出现了弹两次的情况，嗐。
 好在 Esc 可以一次性关掉，所以感觉也还好。
 回头我要是发现什么复现的线索再来补充更详细的信息吧~
